sudo: false
language:
  - erlang
otp_release:
  - 18.3
  - 18.2
  - 18.1
  - 18.0
  - 17.5
  - 17.4
  - 17.3
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R15B03
  - R15B02
  - R15B01
  - R15B
script:
  - "[[ ${TRAVIS_OTP_RELEASE} != 18.3 ]] || make elvis"
  - make
  - make .rebar/DEV_MODE deps test_cli xref eunit
  - "[[ ${TRAVIS_OTP_RELEASE} = R15* ]] || make test_cli_ssl"
  - "[[ ${TRAVIS_OTP_RELEASE} != 18.3 ]] || make dialyzer"
  - make clean .rebar/BARE_MODE # TEST BARE_MODE AS WELL
  - make
  - make .rebar/DEV_MODE deps test_cli xref
  - "[[ ${TRAVIS_OTP_RELEASE} = R15* ]] || make test_cli_ssl"
  - "[[ ${TRAVIS_OTP_RELEASE} != 18.3 ]] || make dialyzer"
