---
name: CI
on:
  push:
    branches:
      - github*
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 0 * * *
jobs:
  ci:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        otp_vsn:
          - '19'
          - '19.1'
          - '19.2'
          - '19.3'
          - '20'
          - '20.1'
          - '20.2'
          - '20.3'
          - '21'
          - '21.1'
          - '21.2'
          - '21.3'
          - '22'
          - '22.1'
          - '22.2'
          - '22.3'
          - '23'
          - '23.1'
          - '23.2'
          - '23.3'
          - '24.0'
          - 'latest'
    name: 'ci-erl:${{ matrix.otp_vsn }}'
    runs-on: ubuntu-latest
    container:
      image: 'erlang:${{ matrix.otp_vsn }}'
    steps:
      - shell: bash
        run: |
          apt-get update
          apt-get -y install tcl tcl-dev gettext
          cd /usr/src/
          wget https://github.com/git/git/archive/v2.18.0.tar.gz -O git.tar.gz
          tar -xf git.tar.gz
          cd git-*
          make prefix=/usr/local all
          make prefix=/usr/local install
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # DEV_MODE

      # - shell: bash
      #   run: make
      - shell: bash
        run: make clean .rebar/DEV_MODE
      - shell: bash
        run: make all xref eunit
      - if: ${{ matrix.otp_vsn == 'latest' }}
        shell: bash
        run: make test_cli dialyzer
      - if: ${{ matrix.otp_vsn == 'latest' }}
        shell: bash
        run: make elvis docs

      # BARE_MODE

      - shell: bash
        run: make clean .rebar/BARE_MODE
      - shell: bash
        run: make all xref # eunit
      - if: ${{ matrix.otp_vsn == 'latest' }}
        shell: bash
        run: make test_cli dialyzer

      # MISC

      - if: ${{ matrix.otp_vsn == 'latest' }}
        shell: bash
        run: make elvis docs
